- Make a tensor below with Python:

  $$
  \begin{bmatrix}   \begin{bmatrix}   23 & 50 \\   7 & 12 \\   \end{bmatrix}   \begin{bmatrix}   57 & 67 \\   99 & 43   \end{bmatrix} \\    \begin{bmatrix}   75 & 21 \\   57 & 12 \\   \end{bmatrix}   \begin{bmatrix}   87 & 26 \\   18 & 84   \end{bmatrix}   \end{bmatrix}
  $$

- Multiply the following matrix:

  $$
  A =
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  \begin{bmatrix}
  17 \\
  22 \\
  19
  \end{bmatrix}
  $$

- Translate, calculate determinants, and inverse to the matrix below:

  $$
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  $$


In [1]:
# Import library used
import numpy as np

In [3]:
# 1. Make a tensor below with python
tensor = np.array([
    [[23, 50], [7, 12]], 
    [[57, 67], [99, 43]],
    [[75, 21], [57, 12]],
    [[87, 26], [18, 84]]])

tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [4]:
# Multiply the following matrix
A = np.array([
    [23,50,19],
    [7, 12, 109],
    [57, 67, 98]
])

B = np.array([
    [17, 22, 19]
])

A*B

array([[ 391, 1100,  361],
       [ 119,  264, 2071],
       [ 969, 1474, 1862]])

In [5]:
# Do transpotions, calculate determinants, and
# Inverse of the matrix below:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [6]:
tranposeA = A.transpose()
tranposeA

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [7]:
determinanA = np.linalg.det(A)
determinanA

131344.0000000002

In [8]:
inverseA = np.linalg.inv(A)
inverseA

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])