In [1]:
import numpy as np

In [4]:
# 1. Buatlah Tensor di bawah ini dengan Python
tensor = np.array([
    [[23, 50], [7, 12]], 
    [[57, 67], [99, 43]],
    [[75, 21], [57, 12]],
    [[87, 26], [18, 84]]])

In [5]:
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [12]:
# Lakukan perkalian terhadap matrix berikut
A = np.array([
    [23,50,19],
    [7, 12, 109],
    [57, 67, 98]
])

B = np.array([
    [17, 22, 19]
])

In [11]:
A*B

array([[ 391, 1100,  361],
       [ 119,  264, 2071],
       [ 969, 1474, 1862]])

In [13]:
# Lakukan Transpose, hitung determinan, dan 
# inverse terhadap matrix dibawah ini:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [15]:
tranposeA = A.transpose()
tranposeA

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [18]:
determinanA = np.linalg.det(A)
determinanA

131344.0000000002

In [20]:
inverseA = np.linalg.inv(A)
inverseA

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])